[package]
name = "advent_of_code_2023"
version = "1.0.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
nom = "7.1.3"

[lints.clippy]
pedantic = "deny"
must_use_candidate = "allow"
missing-errors-doc = "allow"
missing-panics-doc = "allow"